import { Header } from "@/components/header";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export default function LegalPage() {
  return (
    <div className="min-h-screen bg-white dark:bg-zinc-950 font-sans text-zinc-900 dark:text-zinc-100">
      <Header />

      <main className="container mx-auto px-4 py-12 max-w-3xl">
        <div className="mb-8">
          <Link
            href="/"
            className="inline-flex items-center text-sm font-medium text-zinc-500 dark:text-zinc-400 hover:text-red-700 dark:hover:text-red-400 transition-colors"
          >
            <ArrowLeft className="w-4 h-4 mr-2" />
            Back to Journal
          </Link>
        </div>

        <h1 className="text-4xl font-serif font-bold text-zinc-900 dark:text-zinc-100 mb-8 border-b border-zinc-200 dark:border-zinc-700 pb-6">
          Disclaimer & Terms
        </h1>

        <div className="prose prose-zinc dark:prose-invert max-w-none font-serif text-zinc-700 dark:text-zinc-300 leading-relaxed space-y-6">
          <h2 className="text-xl font-bold text-zinc-900 dark:text-zinc-100 mt-8">About The Keele Street Journal</h2>
          <p>
            The Keele Street Journal is an AI-powered, automated financial newspaper created for
            educational purposes. It is designed to provide{" "}
            <a href="https://www.yorku.ca" target="_blank" rel="noopener noreferrer" className="text-red-700 dark:text-red-400 underline hover:text-red-900 dark:hover:text-red-300">York University</a>{" "}
            economics students with daily market analysis, campus news, and economic insights.
          </p>

          <h2 className="text-xl font-bold text-zinc-900 dark:text-zinc-100 mt-8">AI-Generated Content</h2>
          <p>
            The majority of articles, opinion columns, and analysis pieces published on this site are
            generated by artificial intelligence (Google Gemini). Opinion columns are written by
            <strong> fictional characters</strong> with fictional names &mdash; they do not represent
            real individuals, and their views do not reflect the opinions of any real person or
            organization. These fictional voices are used solely to present diverse editorial
            perspectives on real-world news events.
          </p>

          <h2 className="text-xl font-bold text-zinc-900 dark:text-zinc-100 mt-8">News Sources & Attribution</h2>
          <p>
            The underlying news stories and market data referenced throughout this publication are
            real and sourced from publicly available RSS feeds and financial data providers,
            including:
          </p>
          <ul className="list-disc pl-6 space-y-1">
            <li>
              <a href="https://financialpost.com" target="_blank" rel="noopener noreferrer" className="text-red-700 dark:text-red-400 underline hover:text-red-900 dark:hover:text-red-300">Financial Post</a>
            </li>
            <li>
              <a href="https://www.cbc.ca/news/business" target="_blank" rel="noopener noreferrer" className="text-red-700 dark:text-red-400 underline hover:text-red-900 dark:hover:text-red-300">CBC Business</a>
            </li>
            <li>
              <a href="https://www.bbc.com/news/business" target="_blank" rel="noopener noreferrer" className="text-red-700 dark:text-red-400 underline hover:text-red-900 dark:hover:text-red-300">BBC Business</a>
            </li>
            <li>
              <a href="https://www.cnbc.com" target="_blank" rel="noopener noreferrer" className="text-red-700 dark:text-red-400 underline hover:text-red-900 dark:hover:text-red-300">CNBC</a>
            </li>
            <li>
              <a href="https://www.yorku.ca/yfile" target="_blank" rel="noopener noreferrer" className="text-red-700 dark:text-red-400 underline hover:text-red-900 dark:hover:text-red-300">YFile (York University)</a>
            </li>
            <li>
              <a href="https://finance.yahoo.com" target="_blank" rel="noopener noreferrer" className="text-red-700 dark:text-red-400 underline hover:text-red-900 dark:hover:text-red-300">Yahoo Finance</a> (market data)
            </li>
          </ul>
          <p>
            We do not reproduce or republish original articles in full. Our AI reads publicly
            available headlines and summaries from RSS feeds, then generates original editorial
            content inspired by the day&apos;s news. When referencing any news source or institution, we
            link directly to their website so readers can access the original reporting.
          </p>

          <h2 className="text-xl font-bold text-zinc-900 dark:text-zinc-100 mt-8">Not Financial Advice</h2>
          <p>
            Nothing published on The Keele Street Journal constitutes financial, investment, legal,
            or tax advice. All market analysis and commentary is generated by AI for educational and
            informational purposes only. Readers should consult qualified professionals before making
            any financial decisions.
          </p>

          <h2 className="text-xl font-bold text-zinc-900 dark:text-zinc-100 mt-8">Copyright</h2>
          <p>
            All original AI-generated content on this site is the property of The Keele Street
            Journal. Stock photography used on this site is sourced from{" "}
            <a href="https://unsplash.com" target="_blank" rel="noopener noreferrer" className="text-red-700 dark:text-red-400 underline hover:text-red-900 dark:hover:text-red-300">Unsplash</a>{" "}
            under their free-to-use license. Campus images are sourced from{" "}
            <a href="https://www.yorku.ca/yfile" target="_blank" rel="noopener noreferrer" className="text-red-700 dark:text-red-400 underline hover:text-red-900 dark:hover:text-red-300">YFile</a>{" "}
            RSS feeds.
          </p>

          <h2 className="text-xl font-bold text-zinc-900 dark:text-zinc-100 mt-8">Contact</h2>
          <p>
            For questions, concerns, or takedown requests, please reach out via{" "}
            <a href="https://www.linkedin.com/in/omarsaleh001" target="_blank" rel="noopener noreferrer" className="text-red-700 dark:text-red-400 underline hover:text-red-900 dark:hover:text-red-300">LinkedIn</a>.
          </p>
        </div>
      </main>
    </div>
  );
}
